cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router

include_subgraph_errors:
  all: true

headers:
  all:
    request:
      - propagate:
          named: authorization

authentication:
  router:
    jwt:
      jwks:
        - url: <idp jwks url>
      header_name: Authorization
      header_value_prefix: Bearer

authorization:
  directives:
    enabled: true

